// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTimeGetParams creates a new TimeGetParams object
// no default values defined in spec.
func NewTimeGetParams() TimeGetParams {

	return TimeGetParams{}
}

// TimeGetParams contains all the bound params for the time get operation
// typically these are obtained from a http.Request
//
// swagger:parameters TimeGet
type TimeGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Timezone to return
	  In: query
	*/
	Timezone *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewTimeGetParams() beforehand.
func (o *TimeGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qTimezone, qhkTimezone, _ := qs.GetOK("timezone")
	if err := o.bindTimezone(qTimezone, qhkTimezone, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *TimeGetParams) bindTimezone(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Timezone = &raw

	return nil
}
