// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TimeGetHandlerFunc turns a function with the right signature into a time get handler
type TimeGetHandlerFunc func(TimeGetParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TimeGetHandlerFunc) Handle(params TimeGetParams) middleware.Responder {
	return fn(params)
}

// TimeGetHandler interface for that can handle valid time get params
type TimeGetHandler interface {
	Handle(TimeGetParams) middleware.Responder
}

// NewTimeGet creates a new http.Handler for the time get operation
func NewTimeGet(ctx *middleware.Context, handler TimeGetHandler) *TimeGet {
	return &TimeGet{Context: ctx, Handler: handler}
}

/*TimeGet swagger:route GET /time timeGet

Returns time of day.

*/
type TimeGet struct {
	Context *middleware.Context
	Handler TimeGetHandler
}

func (o *TimeGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTimeGetParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
