// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TimePostHandlerFunc turns a function with the right signature into a time post handler
type TimePostHandlerFunc func(TimePostParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TimePostHandlerFunc) Handle(params TimePostParams) middleware.Responder {
	return fn(params)
}

// TimePostHandler interface for that can handle valid time post params
type TimePostHandler interface {
	Handle(TimePostParams) middleware.Responder
}

// NewTimePost creates a new http.Handler for the time post operation
func NewTimePost(ctx *middleware.Context, handler TimePostHandler) *TimePost {
	return &TimePost{Context: ctx, Handler: handler}
}

/*TimePost swagger:route POST /time timePost

Returns time of day.

*/
type TimePost struct {
	Context *middleware.Context
	Handler TimePostHandler
}

func (o *TimePost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTimePostParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
