// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi timeofday
Return the time of day. Timezone optional.


    Schemes:
      http
    Host: localhost
    BasePath: /timeofday/v1
    Version: 0.1.0
    License: apache-2.0
    Contact: Elf Sternberg<elf.sternberg@gmail.com> https://github.com/elfsternberg/go-timeofday

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
